artifacts_root: artifacts
default_dataset: samsum

data_ingestion:
  root_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  status_file_name: status.txt
  required_splits: ["train", "validation", "test"]

data_transformation:
  root_dir: artifacts/data_transformation
  tokenizer_name: google/pegasus-cnn_dailymail

model_trainer:
  root_dir: artifacts/model_trainer
  model_ckpt: google/pegasus-cnn_dailymail

model_evaluation:
  root_dir: artifacts/model_evaluation
  generation:
    length_penalty: 0.8
    num_beams: 8
    max_length: 128
    min_length: 12
  metrics:
    sample_size: 50
    names: ["rouge1", "rouge2", "rougeL", "rougeLsum"]

experiment_tracking:
  root_dir: artifacts/experiments

datasets:
  samsum:
    description: "Dialogues summarization dataset from Samsum."
    ingestion:
      type: zip
      source_url: https://github.com/atharvayeola/text-summarizer/raw/main/data/summarizer-data.zip
      archive_filename: samsum.zip
      extracted_folder_name: samsum_dataset
    columns:
      input_text: dialogue
      target_text: summary
    splits:
      train: train
      validation: validation
      test: test
    max_input_length: 1024
    max_target_length: 128
    preprocessing_fn:

  cnn_dailymail:
    description: "News summarization dataset from CNN/DailyMail (via Hugging Face)."
    ingestion:
      type: huggingface
      dataset_name: cnn_dailymail
      subset: 3.0.0
    columns:
      input_text: article
      target_text: highlights
    splits:
      train: train
      validation: validation
      test: test
    max_input_length: 1024
    max_target_length: 128
    preprocessing_fn:
